CREATE TABLE ex1_employees (
	ID			INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NOMBRES			VARCHAR(35)	NOT NULL,
	APELLIDOS		VARCHAR(35),
	DNI				VARCHAR(15),
	FECHA_NACIMIENTO	DATE,
	GENERO			VARCHAR(20),
	ESTADO			INT	DEFAULT 0,
	CREADO_POR		VARCHAR(40) DEFAULT 'admin',
	FECHA_CREACION	TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ex1_departments (
	ID			INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	NOMBRE			VARCHAR(30)	UNIQUE,
	DESCRIPCION		VARCHAR(180),
	CREADO_POR		VARCHAR(40) DEFAULT 'admin',
	FECHA_CREACION	TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ex1_managers (
	ID			INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	ID_EMPLOYEE		INT,
	DESDE			DATE,
	HASTA			DATE,
	CREADO_POR		VARCHAR(40) DEFAULT 'admin',
	FECHA_CREACION	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_managers FOREIGN KEY (ID_EMPLOYEE) REFERENCES EX1_EMPLOYEES(ID));
	
CREATE TABLE ex1_salaries (
	ID			INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	ID_EMPLOYEE		INT,
	DESDE			DATE,
	HASTA			DATE,
	SALARIO			DOUBLE PRECISION	DEFAULT 0.00,
	CREADO_POR		VARCHAR(40) DEFAULT 'admin',
	FECHA_CREACION	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_managers FOREIGN KEY (ID_EMPLOYEE) REFERENCES EX1_EMPLOYEES(ID));

CREATE TABLE ex1_depto_manager (
	ID			INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	ID_EMPLOYEE		INT,
	ID_DEPARTMENTS		INT,	
	DESDE			DATE,
	HASTA			DATE,
	CREADO_POR		VARCHAR(40) DEFAULT 'admin',
	FECHA_CREACION	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_depto_manager01 FOREIGN KEY (ID_EMPLOYEE) REFERENCES EX1_EMPLOYEES(ID),
	CONSTRAINT fk_depto_manager02 FOREIGN KEY (ID_DEPARTMENTS) REFERENCES EX1_DEPARTMENTS(ID)
);

CREATE TABLE ex1_titles (
	ID			INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	ID_EMPLOYEE		INT,
	NOMBRE			VARCHAR(60),	
	DESDE			DATE,
	HASTA			DATE,
	CREADO_POR		VARCHAR(40) DEFAULT 'admin',
	FECHA_CREACION	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_depto_manager01 FOREIGN KEY (ID_EMPLOYEE) REFERENCES EX1_EMPLOYEES(ID)
);
